// build-data.js
// Run this with: node build-data.js
// It scans your league folder (created by go-nfl-fantasy) and combines
// all per-year JSON files into one data.js file that index.html loads.

const fs = require('fs');
const path = require('path');

// CHANGE THIS to your league folder name if different
const LEAGUE_FOLDER = '856875-league-name';

const FILES = {
  managers: 'managers-history.json',
  standings: 'regular-season-standings-history.json',
  matchups: 'matchup-history.json',
  drafts: 'draft-history.json',
  trades: 'trade-history.json',
  playerStats: 'player-matchup-statistics-history.json',
  endStandings: 'end-standings-history.json',
  playoffs: 'playoff-history.json'
};

function loadAllYears(leagueDir, filename) {
  const combined = [];
  const years = fs.readdirSync(leagueDir).filter(name => {
    const full = path.join(leagueDir, name);
    return fs.statSync(full).isDirectory() && /^\d{4}$/.test(name);
  });

  years.forEach(year => {
    const filePath = path.join(leagueDir, year, filename);
    if (fs.existsSync(filePath)) {
      try {
        const raw = fs.readFileSync(filePath, 'utf8');
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed)) {
          combined.push(...parsed);
        }
      } catch (e) {
        console.warn(`Could not parse ${filePath}: ${e.message}`);
      }
    }
  });

  return combined;
}

// Manager name cleanup — maps raw scraped names to clean display names.
// Add more entries here any time a name looks off.
const NAME_MAP = {
  'frank': 'Frank',
  'm': 'Matt',
  'The real big dumper': 'Blake',
  'Taylor I': 'Taylor'
};

function cleanManagerName(name) {
  return NAME_MAP[name] || name;
}

function main() {
  if (!fs.existsSync(LEAGUE_FOLDER)) {
    console.error(`Folder "${LEAGUE_FOLDER}" not found. Edit LEAGUE_FOLDER at the top of this script to match your folder name.`);
    process.exit(1);
  }

  const data = {};
  for (const [key, filename] of Object.entries(FILES)) {
    data[key] = loadAllYears(LEAGUE_FOLDER, filename);
    console.log(`Loaded ${data[key].length} records for ${key}`);
  }

  // Clean up manager names across all manager records
  data.managers.forEach(m => {
    if (m.managerName) m.managerName = cleanManagerName(m.managerName);
    if (m.coManagerName) m.coManagerName = cleanManagerName(m.coManagerName);
  });
  console.log('Applied manager name cleanup');

  // Manual overrides for incorrect scraped data
  // 2022: Jake (teamId 1) finished 1st, Matt (teamId 7) finished 2nd (scraper had them swapped)
  const jake2022 = data.endStandings.find(r => String(r.year) === '2022' && String(r.teamId) === '1');
  const matt2022 = data.endStandings.find(r => String(r.year) === '2022' && String(r.teamId) === '7');
  if (jake2022 && matt2022) {
    jake2022.rank = 1;
    matt2022.rank = 2;
    console.log('Applied 2022 override: Jake (team 1) → 1st, Matt (team 7) → 2nd');
  } else {
    console.warn('Could not find 2022 teams for override');
  }

  // Load the global players.json (player ID -> name map), sits at the league root
  const playersPath = path.join(LEAGUE_FOLDER, 'players.json');
  data.players = [];
  if (fs.existsSync(playersPath)) {
    try {
      const raw = fs.readFileSync(playersPath, 'utf8');
      data.players = JSON.parse(raw);
      console.log(`Loaded ${data.players.length} records for players (ID-to-name map)`);
    } catch (e) {
      console.warn(`Could not parse ${playersPath}: ${e.message}`);
    }
  }

  const output = `// Auto-generated by build-data.js\nwindow.initLeague(${JSON.stringify(data)});\n`;
  fs.writeFileSync('data.js', output);
  console.log('\n✅ data.js created successfully!');
  console.log('Now open index.html in your browser to see your dashboard.');
}

main();
